sudo: false

language: elixir

elixir:
  - 1.2

otp_release:
  - 18.0
  - 18.1
  - 18.2

install:
  - mix local.hex --force
  - mix deps.get

script:
  - mix test

notifications:
  recipients:
    - alchemist.philippines@gmail.com