sudo: false

language: elixir

elixir:
  - 1.2

otp_release:
  - 18.0
  - 18.1
  - 18.2

install:
  - mix local.hex --force
  - mix deps.get

script:
  - mix test

matrix:
  include:
    - elixir: 1.2.0
      otp_release: 18.0
    - elixir: 1.2.1
      otp_release: 18.1
    - elixir: 1.2.2
      otp_release: 18.1
    - elixir: 1.2.3
      otp_release: 18.1
    - elixir: 1.2.4
      otp_release: 18.1
    - elixir: 1.2.5
      otp_release: 18.1
      otp_release: 18.2

notifications:
  recipients:
    - alchemist.philippines@gmail.com